<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- ========================== -->
    <!--            Variables       -->
    <!-- ========================== -->
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>

    <!-- ====================================================================================== -->


    <!-- ========================== -->
    <!--   Create Macros (Functions)-->
    <!-- ========================== -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <material name="Blue"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            </collision>
            <xacro:cylinder_inerta m="1.0" r="${wheel_radius}" h="${wheel_length}" xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
        </link>
    </xacro:macro>

    <!-- ====================================================================================== -->

    <!-- ========================== -->
    <!--            LINKS           -->
    <!-- ========================== -->
    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>


    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
            <material name="Green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="5.0" l="${base_length}" w="${base_width}" h="${base_height}"  xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>


    <link name="Caster_wheel">
        <visual>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:ball_inertia m="0.1" r="0.05" xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>

    <link name="base_footprint"/>

    <!-- ====================================================================================== -->

    <!-- ========================== -->
    <!--            JOINTS          -->
    <!-- ========================== -->
    <joint name="right_wheel_Joint" type="revolute">
        <origin xyz="-0.15 -0.225 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="100"/>
    </joint>


    <joint name="left_wheel_Joint" type="revolute">
        <origin xyz="-0.15 0.225 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <axis xyz="0.0 -1.0 0.0"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="100"/>
    </joint>


    <joint name="base_caster_wheel_joint" type="fixed">
        <origin xyz="0.2 0.0 -0.05"/>
        <parent link="base_link"/>
        <child link="Caster_wheel"/>
    </joint>

    <joint name="base_joint" type="fixed">
        <origin xyz="0.0 0.0 -0.1" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="base_footprint"/>
    </joint>
</robot>